theme = "nord"

[editor.gutters]
layout = ["diagnostics", "spacer", "diff"] # But no "line-numbers".

[keys.insert]
j = { k = "normal_mode" }

[keys.insert."C-k"]
- = { ">" = "@→"}
O = { K = "@✓"}

[keys.normal]
"ö" = "command_mode"
"-" = "search"
"ä" = "goto_next_paragraph"
"Ä" = "goto_prev_paragraph"
