theme = "nord"

[editor.gutters]
layout = ["diagnostics", "spacer", "diff"] # But no "line-numbers".

[keys.insert]
j = { k = "normal_mode" }

[keys.insert."C-k"]
- = { ">" = ["normal_mode", ":insert-output echo '→'", "move_char_right", "insert_mode"]}
O = { K = ["normal_mode", ":insert-output echo '✓'", "move_char_right", "insert_mode"]}

[keys.normal]
"ö" = "command_mode"
"-" = "search"
"ä" = "goto_next_paragraph"
"Ä" = "goto_prev_paragraph"
